# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(max_length=15),
        ),
    ]
