# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20160612_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lattitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
